### ISSUE TITLE
Error importing to database

### ISSUE THREAD

**Issue by shubhbansal9** [CodeFoxLk/quizzle_public#1]
![image](https://user-images.githubusercontent.com/90069182/155537137-279825d0-15d8-4b98-80af-76e037e31e54.png)
I have followed all the steps in your video and that google document and have connected my project to firebase but it is still not importing the files when you've asked to comment the code and uncomment the other one. When I run 'flutter clean' followed by 'flutter run', the terminal stops at the screen shown in the screenshot. Kindly help me fix this. And you've done a wonderful job with this project.

**Comment by CodeFoxLk** [comment]
it seems a firebase error. could you post the complete error please?

**Comment by shubhbansal9** [comment]
> 

Actually it was an emulator error, due to googleplay services. I ran the project on my physical device and it worked.
