### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by jish-44** [CodeFoxLk/quizzle_public#3]
Plugin error: File '~/.local/share/Google/AndroidStudio2021.2/Kotlin/lib/kotlin-idea.jar' contains invalid plugin descriptor
how to solve this

**Comment by jish-44** [comment]
💪 Building with sound null safety 💪

Running Gradle task 'assembleRelease'...                        
Building with Flutter multidex support enabled.
lib/controllers/common/drawer_controller.dart:8:32: Error: Method not found: 'ZoomDrawerController'.
  final zoomDrawerController = ZoomDrawerController();
                               ^^^^^^^^^^^^^^^^^^^^
lib/screens/home/home_screen.dart:30:9: Error: No named parameter with the name 'backgroundColor'.
        backgroundColor: Colors.white.withOpacity(0.5),
        ^^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_drawer-3.0.2/lib/flutter_zoom_drawer.dart:34:9: Context: Found this candidate, but the arguments don't match.
  const ZoomDrawer({
        ^^^^^^^^^^
lib/screens/leaderboard/leaderboard_screen.dart:12:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback((d) {
                     ^


FAILURE: Build failed with an exception.

* Where:
Script '/home/jishnu/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/jishnu/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s
Running Gradle task 'assembleRelease'...                           76.0s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by jish-44** [comment]
I'm also getting these errors

**Comment by CodeFoxLk** [comment]
pull new commit and  run flutter pub upgrade

**Comment by jish-44** [comment]
Thaks bro
